// GPU inverse 9/7 (irreversible) DWT — float port of the CPU `idwt_level_f32`
// in `rust/htj2k-core/src/decode.rs`. Same optimised strategy as `idwt53.ts`:
// one workgroup per line, lifting in workgroup shared memory with intra-line
// parallelism (barriers between steps), no global scratch buffer. Float, with
// the 9/7 K pre-scale and four lifting steps `aug -= a*(l+r)`; the four steps
// alternate which deinterleaved region is `aug` (low/high) by step parity. The
// caller converts the normalized output to pixels (`irvToPixels`).
//
// The uniform struct + f32 bind group layout are typed TypeGPU resources
// generated by tgpu-gen (`idwt97.gen.ts`); the compute logic references them as
// externals, stitched together by `tgpu.resolveWithContext`.
import tgpu from "typegpu";
import * as d from "typegpu/data";
import { getDevice } from "./device";
import { Lvl, layout0 } from "./idwt97.gen";

const WG = 64;
const MAXLINE = 2048; // max samples/line; 2048*4 = 8 KiB shared mem per workgroup
const TEMPLATE = /* wgsl */ `
const K: f32 = 1.230174104914001;
const STEP0: f32 = 0.443506852043971;
const STEP1: f32 = 0.882911075530934;
const STEP2: f32 = -0.052980118572961;
const STEP3: f32 = -1.586134342059924;

fn clampr(j: i32, n: u32) -> u32 {
  if (j < 0) { return 0u; }
  if (u32(j) >= n) { return n - 1u; }
  return u32(j);
}
fn step_coeff(j: u32) -> f32 {
  if (j == 0u) { return STEP0; }
  if (j == 1u) { return STEP1; }
  if (j == 2u) { return STEP2; }
  return STEP3;
}

var<workgroup> sh: array<f32, ${MAXLINE}u>;  // sh[0..nl) low, sh[nl..nl+nh) high

// Inverse 9/7 lifting in shared memory, parallel over the line (t-strided
// threads), with a barrier after the K pre-scale and after each of the four
// steps. Even-index steps act on low (aug), odd on high.
fn lift(t: u32, nl: u32, nh: u32, even: u32) {
  for (var i: u32 = t; i < nl; i = i + ${WG}u) { sh[i] = sh[i] * K; }
  for (var i: u32 = t; i < nh; i = i + ${WG}u) { sh[nl + i] = sh[nl + i] * (1.0 / K); }
  workgroupBarrier();
  for (var j: u32 = 0u; j < 4u; j = j + 1u) {
    let a = step_coeff(j);
    let aug_low = (j & 1u) == 0u;
    let aug_off = select(nl, 0u, aug_low);
    let oth_off = select(0u, nl, aug_low);
    let aug_n = select(nh, nl, aug_low);
    let oth_n = select(nl, nh, aug_low);
    var ev: u32 = even; if (!aug_low) { ev = 1u - even; }
    let off: i32 = select(1i, 0i, ev == 1u);
    for (var i: u32 = t; i < aug_n; i = i + ${WG}u) {
      let l = sh[oth_off + clampr(i32(i) + off - 1, oth_n)];
      let r = sh[oth_off + clampr(i32(i) + off, oth_n)];
      sh[aug_off + i] = sh[aug_off + i] - a * (l + r);
    }
    workgroupBarrier();
  }
}

// Interleave shared low/high into out[out_base + p*out_stride], parallel over p.
// sel: 0 -> hbuf, 1 -> outbuf.
fn scatter(t: u32, nl: u32, nh: u32, even: u32, out_base: u32, out_stride: u32, sel: u32) {
  let width = nl + nh;
  let low_phase = select(1u, 0u, even == 1u);
  for (var p: u32 = t; p < width; p = p + ${WG}u) {
    let idx = p >> 1u;
    var v: f32;
    if ((p & 1u) == low_phase) { v = sh[idx]; } else { v = sh[nl + idx]; }
    let o = out_base + p * out_stride;
    if (sel == 0u) { hbuf[o] = v; } else { outbuf[o] = v; }
  }
}

@compute @workgroup_size(${WG})
fn idwt_h(@builtin(workgroup_id) wid: vec3u, @builtin(local_invocation_id) lid: vec3u) {
  let ry = wid.x;
  if (ry >= L.rh0 + L.rh1) { return; }
  let t = lid.x;
  let nl = L.rw0; let nh = L.rw1; let width = L.out_w;
  let a_size = L.rh0 * L.out_w;
  var low_is_inbuf = false;
  var low_off: u32 = 0u; var high_off: u32 = 0u; var srow: u32 = 0u;
  if (ry < L.rh0) {
    low_is_inbuf = true; srow = ry;
    low_off = ry * L.rw0; high_off = L.hl_off + ry * L.rw1;
  } else {
    srow = ry - L.rh0;
    low_off = L.lh_off + srow * L.rw0; high_off = L.hh_off + srow * L.rw1;
  }
  for (var i: u32 = t; i < nl; i = i + ${WG}u) {
    sh[i] = select(coeffs[low_off + i], inbuf[low_off + i], low_is_inbuf);
  }
  for (var i: u32 = t; i < nh; i = i + ${WG}u) {
    sh[nl + i] = coeffs[high_off + i];
  }
  workgroupBarrier();
  let out_base = select(a_size + srow * L.out_w, ry * L.out_w, ry < L.rh0);
  if (width == 1u) {
    if (t == 0u) { hbuf[out_base] = select(sh[nl] * 0.5, sh[0], L.even_x == 1u); }
    return;
  }
  lift(t, nl, nh, L.even_x);
  scatter(t, nl, nh, L.even_x, out_base, 1u, 0u);
}

@compute @workgroup_size(${WG})
fn idwt_v(@builtin(workgroup_id) wid: vec3u, @builtin(local_invocation_id) lid: vec3u) {
  let cx = wid.x;
  if (cx >= L.out_w) { return; }
  let t = lid.x;
  let nl = L.rh0; let nh = L.rh1; let height = L.out_h;
  let a_size = L.rh0 * L.out_w;
  for (var y: u32 = t; y < nl; y = y + ${WG}u) {
    sh[y] = hbuf[y * L.out_w + cx];
  }
  for (var y: u32 = t; y < nh; y = y + ${WG}u) {
    sh[nl + y] = hbuf[a_size + y * L.out_w + cx];
  }
  workgroupBarrier();
  if (height == 1u) {
    if (t == 0u) { outbuf[cx] = select(sh[nl] * 0.5, sh[0], L.even_y == 1u); }
    return;
  }
  lift(t, nl, nh, L.even_y);
  scatter(t, nl, nh, L.even_y, cx, L.out_w, 1u);
}
`;

export interface DwtInput97 {
  descriptor: Uint32Array;
  coeffs: Float32Array;
  width: number;
  height: number;
}

// Optional GPU float→pixel conversion (a separate, reusable pass — the DWT keeps
// its float output as a general-purpose primitive). Port of `irv_to_pixels`
// (`lib.rs`): scale by 2^bit_depth, round half-away-from-zero, clamp, level
// shift. Params are precomputed on the CPU so the shader matches exactly.
const Conv = d.struct({
  n: d.u32, mul: d.f32, flLow: d.f32, flUp: d.f32,
  sLow: d.i32, sUp: d.i32, add: d.i32, _pad: d.u32,
});
const convLayout = tgpu.bindGroupLayout({
  C: { uniform: Conv },
  src: { storage: (n: number) => d.arrayOf(d.f32, n), access: "readonly" },
  dst: { storage: (n: number) => d.arrayOf(d.i32, n), access: "mutable" },
});
const CONVERT_TEMPLATE = /* wgsl */ `
@compute @workgroup_size(64)
fn convert(@builtin(global_invocation_id) g: vec3u) {
  if (g.x >= C.n) { return; }
  let t = src[g.x] * C.mul;
  var v: i32 = i32(t + select(-0.5, 0.5, t >= 0.0)); // round half away from zero
  if (!(t >= C.flLow)) { v = C.sLow; }               // clamp to dynamic range
  if (!(t < C.flUp)) { v = C.sUp; }
  dst[g.x] = v + C.add;                               // DC level shift
}
`;

interface Pipe {
  root: ReturnType<typeof tgpu.initFromDevice>;
  device: GPUDevice;
  pipeH: GPUComputePipeline;
  pipeV: GPUComputePipeline;
  pipeConv: GPUComputePipeline;
}
let pipeCache: Promise<Pipe> | undefined;

async function getPipe(): Promise<Pipe> {
  pipeCache ??= (async () => {
    const device = await getDevice();
    const root = tgpu.initFromDevice({ device });
    const { code, usedBindGroupLayouts } = tgpu.resolveWithContext({
      template: TEMPLATE,
      externals: { ...layout0.bound },
      names: "strict",
    });
    const module = device.createShaderModule({ code });
    const pipeLayout = device.createPipelineLayout({
      bindGroupLayouts: usedBindGroupLayouts.map((l) => root.unwrap(l)),
    });
    const pipeH = device.createComputePipeline({ layout: pipeLayout, compute: { module, entryPoint: "idwt_h" } });
    const pipeV = device.createComputePipeline({ layout: pipeLayout, compute: { module, entryPoint: "idwt_v" } });

    // Float→pixel conversion pipeline (its own layout: f32 src + i32 dst).
    const conv = tgpu.resolveWithContext({ template: CONVERT_TEMPLATE, externals: { ...convLayout.bound }, names: "strict" });
    const convMod = device.createShaderModule({ code: conv.code });
    const convPipeLayout = device.createPipelineLayout({
      bindGroupLayouts: conv.usedBindGroupLayouts.map((l) => root.unwrap(l)),
    });
    const pipeConv = device.createComputePipeline({ layout: convPipeLayout, compute: { module: convMod, entryPoint: "convert" } });
    return { root, device, pipeH, pipeV, pipeConv };
  })();
  return pipeCache;
}

// Pooled f32 buffers, reused/grown across calls (see idwt53.ts for rationale).
type Root = Awaited<ReturnType<typeof getPipe>>["root"];
function makePool(root: Root, cap: number, ccap: number) {
  const A = (n: number) => d.arrayOf(d.f32, Math.max(1, n));
  return {
    cap, ccap,
    bufA: root.createBuffer(A(cap)).$usage("storage"),
    bufB: root.createBuffer(A(cap)).$usage("storage"),
    hbuf: root.createBuffer(A(cap)).$usage("storage"),
    coeffBuf: root.createBuffer(A(ccap)).$usage("storage"),
    lvlBuf: root.createBuffer(Lvl).$usage("uniform"),
    pixBuf: root.createBuffer(d.arrayOf(d.i32, Math.max(1, cap))).$usage("storage"),
    convBuf: root.createBuffer(Conv).$usage("uniform"),
  };
}
let pool: ReturnType<typeof makePool> | undefined;
function ensurePool(root: Root, imgN: number, coeffLen: number) {
  if (pool && pool.cap >= imgN && pool.ccap >= coeffLen) return pool;
  const cap = Math.max(imgN, pool?.cap ?? 0);
  const ccap = Math.max(coeffLen, pool?.ccap ?? 0);
  if (pool) for (const b of [pool.bufA, pool.bufB, pool.hbuf, pool.coeffBuf, pool.lvlBuf, pool.pixBuf, pool.convBuf]) b.destroy();
  pool = makePool(root, cap, ccap);
  return pool;
}

export interface Idwt97Opts {
  /** When false, skip the full readback and just sync (keep-on-GPU / timing).
   *  Returns null in that case. Default true. */
  readback?: boolean;
  /** When set, run the GPU float→pixel conversion (scale + round + clamp + level
   *  shift) and return Int32Array pixels instead of float samples. */
  pixels?: { bitDepth: number; signed: boolean };
}

/** Run the inverse 9/7 DWT on the GPU. Returns normalized float samples by
 *  default (the DWT is a general-purpose primitive); with `opts.pixels`, runs
 *  the GPU pixel conversion and returns Int32Array pixels. Null when
 *  `opts.readback === false`. */
export async function idwt97Gpu(input: DwtInput97, opts: Idwt97Opts = {}): Promise<Float32Array | Int32Array | null> {
  const { root, device, pipeH, pipeV, pipeConv } = await getPipe();
  const { descriptor: desc, coeffs, width, height } = input;
  const at = (i: number): number => desc[i]!;
  const nLevels = at(1);
  const imgN = width * height;
  const ll0w = at(2), ll0h = at(3), ll0off = at(4);

  const p = ensurePool(root, imgN, coeffs.length);
  device.queue.writeBuffer(root.unwrap(p.coeffBuf), 0, coeffs as BufferSource);
  device.queue.writeBuffer(root.unwrap(p.bufA), 0, coeffs.subarray(ll0off, ll0off + ll0w * ll0h) as BufferSource);

  let inbuf = p.bufA, outbuf = p.bufB;
  for (let lvl = 0; lvl < nLevels; lvl++) {
    const o = 5 + lvl * 12;
    const outW = at(o + 4);
    const rowCount = at(o + 1) + at(o + 3);
    p.lvlBuf.write({
      rw0: at(o), rh0: at(o + 1), rw1: at(o + 2), rh1: at(o + 3),
      out_w: at(o + 4), out_h: at(o + 5), even_x: at(o + 6), even_y: at(o + 7),
      hl_off: at(o + 8), lh_off: at(o + 9), hh_off: at(o + 10), _pad: 0,
    });
    const rawBind = root.unwrap(root.createBindGroup(layout0, {
      L: p.lvlBuf, inbuf, coeffs: p.coeffBuf, hbuf: p.hbuf, outbuf,
    }));

    const enc = device.createCommandEncoder();
    const ph = enc.beginComputePass();
    ph.setPipeline(pipeH); ph.setBindGroup(0, rawBind);
    ph.dispatchWorkgroups(rowCount);
    ph.end();
    const pv = enc.beginComputePass();
    pv.setPipeline(pipeV); pv.setBindGroup(0, rawBind);
    pv.dispatchWorkgroups(outW);
    pv.end();
    device.queue.submit([enc.finish()]);

    [inbuf, outbuf] = [outbuf, inbuf];
  }

  // Optional GPU pixel conversion: f32 samples (in `inbuf`) -> i32 pixels.
  if (opts.pixels) {
    const { bitDepth, signed } = opts.pixels;
    const sUp = 0x7fffffff >> (32 - bitDepth);
    const sLow = -(sUp + 1);
    p.convBuf.write({
      n: imgN, mul: 2 ** bitDepth, flLow: sLow, flUp: -sLow,
      sLow, sUp, add: signed ? 0 : 1 << (bitDepth - 1), _pad: 0,
    });
    const cbind = root.unwrap(root.createBindGroup(convLayout, { C: p.convBuf, src: inbuf, dst: p.pixBuf }));
    const enc = device.createCommandEncoder();
    const pc = enc.beginComputePass();
    pc.setPipeline(pipeConv); pc.setBindGroup(0, cbind);
    pc.dispatchWorkgroups(Math.ceil(imgN / 64));
    pc.end();
    device.queue.submit([enc.finish()]);
    if (opts.readback === false) {
      await device.queue.onSubmittedWorkDone();
      return null;
    }
    const px = (await p.pixBuf.read()) as ArrayLike<number>;
    return Int32Array.from(px).slice(0, imgN);
  }

  if (opts.readback === false) {
    await device.queue.onSubmittedWorkDone();
    return null;
  }
  const result = (await inbuf.read()) as ArrayLike<number>;
  return Float32Array.from(result).slice(0, imgN);
}

/** Convert normalized 9/7 float samples to integer pixels — JS port of
 *  `irv_to_pixels` (`lib.rs`): scale by 2^bit_depth, round half-away-from-zero,
 *  clamp, level shift. `Math.fround` mirrors the Rust f32 multiply. */
export function irvToPixels(coeffs: Float32Array, bitDepth: number, signed: boolean): Int32Array {
  const mul = 2 ** bitDepth;
  const up = (0x7fffffff >> (32 - bitDepth));
  const low = -(up + 1);
  const flUp = -low, flLow = low;
  const half = 1 << (bitDepth - 1);
  const out = new Int32Array(coeffs.length);
  for (let i = 0; i < coeffs.length; i++) {
    const t = Math.fround(coeffs[i]! * mul);
    let v = Math.trunc(t + (t >= 0 ? 0.5 : -0.5));
    if (!(t >= flLow)) v = low;
    if (!(t < flUp)) v = up;
    out[i] = signed ? v : v + half;
  }
  return out;
}
